#server.port=3000
#server.error.include-exception=false
#server.error.include-stacktrace=never
#server.error.include-message=always

server:
  port: 3000
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_db?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: parking
    password: parking-mqds
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate_format_sql: true
#  security:
#    user:
#      name: user
#      password: 12345